#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:broadband-forum-org:tr-069-1-0."""

import core


class InternetGatewayDevice_v1_0(core.Exporter):
  """Represents InternetGatewayDevice_v1_0."""

  def __init__(self, **defaults):
    core.Exporter.__init__(self, defaults=defaults)
    self.Export(objects=['InternetGatewayDevice'])

  class InternetGatewayDevice(core.Exporter):
    """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice."""

    def __init__(self, **defaults):
      core.Exporter.__init__(self, defaults=defaults)
      self.Export(params=['LANDeviceNumberOfEntries',
                          'WANDeviceNumberOfEntries'],
                  objects=['DeviceConfig',
                           'DeviceInfo',
                           'IPPingDiagnostics',
                           'LANConfigSecurity',
                           'Layer3Forwarding',
                           'ManagementServer',
                           'Time',
                           'UserInterface'],
                  lists=['LANDevice',
                         'WANDevice'])

    class DeviceConfig(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.DeviceConfig."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['ConfigFile',
                            'PersistentData'])

    class DeviceInfo(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.DeviceInfo."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['AdditionalHardwareVersion',
                            'AdditionalSoftwareVersion',
                            'Description',
                            'DeviceLog',
                            'EnabledOptions',
                            'FirstUseDate',
                            'HardwareVersion',
                            'Manufacturer',
                            'ManufacturerOUI',
                            'ModelName',
                            'ModemFirmwareVersion',
                            'ProductClass',
                            'ProvisioningCode',
                            'SerialNumber',
                            'SoftwareVersion',
                            'SpecVersion',
                            'UpTime',
                            'VendorConfigFileNumberOfEntries'],
                    lists=['VendorConfigFile'])

      class VendorConfigFile(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['Date',
                              'Description',
                              'Name',
                              'Version'])

    class IPPingDiagnostics(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.IPPingDiagnostics."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['AverageResponseTime',
                            'DSCP',
                            'DataBlockSize',
                            'DiagnosticsState',
                            'FailureCount',
                            'Host',
                            'Interface',
                            'MaximumResponseTime',
                            'MinimumResponseTmie',
                            'NumberOfRepetitions',
                            'SuccessCount',
                            'Timeout'])

    class LANConfigSecurity(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANConfigSecurity."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['ConfigPassword'])

    class LANDevice(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['LANEthernetInterfaceNumberOfEntries',
                            'LANUSBInterfaceNumberOfEntries',
                            'LANWLANConfigurationNumberOfEntries'],
                    objects=['Hosts',
                             'LANHostConfigManagement'],
                    lists=['LANEthernetInterfaceConfig',
                           'LANUSBInterfaceConfig',
                           'WLANConfiguration'])

      class Hosts(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.Hosts."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['HostNumberOfEntries'],
                      lists=['Host'])

        class Host(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['Active',
                                'AddressSource',
                                'HostName',
                                'IPAddress',
                                'InterfaceType',
                                'LeaseTimeRemaining',
                                'MACAddress'])

      class LANEthernetInterfaceConfig(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['DuplexMode',
                              'Enable',
                              'MACAddress',
                              'MACAddressControlEnabled',
                              'MaxBitRate',
                              'Status'],
                      objects=['Stats'])

        class Stats(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['BytesReceived',
                                'BytesSent',
                                'PacketsReceived',
                                'PacketsSent'])

      class LANHostConfigManagement(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['AllowedMACAddresses',
                              'AssociatedConnection',
                              'DHCPLeaseTime',
                              'DHCPRelay',
                              'DHCPServerConfigurable',
                              'DHCPServerEnable',
                              'DNSServers',
                              'DomainName',
                              'IPInterfaceNumberOfEntries',
                              'IPRouters',
                              'MaxAddress',
                              'MinAddress',
                              'PassthroughLease',
                              'PassthroughMACAddress',
                              'ReservedAddresses',
                              'SubnetMask',
                              'UseAllocatedWAN'],
                      lists=['IPInterface'])

        class IPInterface(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['Enable',
                                'IPInterfaceAddressingType',
                                'IPInterfaceIPAddress',
                                'IPInterfaceSubnetMask'])

      class LANUSBInterfaceConfig(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['Enable',
                              'MACAddress',
                              'MACAddressControlEnabled',
                              'Power',
                              'Rate',
                              'Standard',
                              'Status',
                              'Type'],
                      objects=['Stats'])

        class Stats(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['BytesReceived',
                                'BytesSent',
                                'CellsReceived',
                                'CellsSent'])

      class WLANConfiguration(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['AuthenticationServiceMode',
                              'AutoRateFallBackEnabled',
                              'BSSID',
                              'BasicAuthenticationMode',
                              'BasicDataTransmitRates',
                              'BasicEncryptionModes',
                              'BeaconAdvertisementEnabled',
                              'BeaconType',
                              'Channel',
                              'ChannelsInUse',
                              'DeviceOperationMode',
                              'DistanceFromRoot',
                              'Enable',
                              'IEEE11iAuthenticationMode',
                              'IEEE11iEncryptionModes',
                              'InsecureOOBAccessEnabled',
                              'KeyPassphrase',
                              'LocationDescription',
                              'MACAddressControlEnabled',
                              'MaxBitRate',
                              'OperationalDataTransmitRates',
                              'PeerBSSID',
                              'PossibleChannels',
                              'PossibleDataTransmitRates',
                              'RadioEnabled',
                              'RegulatoryDomain',
                              'SSID',
                              'Standard',
                              'Status',
                              'TotalAssociations',
                              'TotalBytesReceived',
                              'TotalBytesSent',
                              'TotalIntegrityFailures',
                              'TotalPSKFailures',
                              'TotalPacketsReceived',
                              'TotalPacketsSent',
                              'WEPEncryptionLevel',
                              'WEPKeyIndex',
                              'WPAAuthenticationMode',
                              'WPAEncryptionModes'],
                      lists=['AssociatedDevice',
                             'PreSharedKey',
                             'WEPKey'])

        class AssociatedDevice(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AssociatedDeviceAuthenticationState',
                                'AssociatedDeviceIPAddress',
                                'AssociatedDeviceMACAddress',
                                'LastPMKId',
                                'LastRequestedMulticastCipher',
                                'LastRequestedUnicastCipher'])

        class PreSharedKey(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AssociatedDeviceMACAddress',
                                'KeyPassphrase',
                                'PreSharedKey'])

        class WEPKey(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['WEPKey'])

    class Layer3Forwarding(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.Layer3Forwarding."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['DefaultConnectionService',
                            'ForwardNumberOfEntries'],
                    lists=['Forwarding'])

      class Forwarding(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['DestIPAddress',
                              'DestSubnetMask',
                              'Enable',
                              'ForwardingMetric',
                              'GatewayIPAddress',
                              'Interface',
                              'MTU',
                              'SourceIPAddress',
                              'SourceSubnetMask',
                              'Status',
                              'Type'])

    class ManagementServer(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.ManagementServer."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['ConnectionRequestPassword',
                            'ConnectionRequestURL',
                            'ConnectionRequestUsername',
                            'DownloadProgressURL',
                            'KickURL',
                            'ParameterKey',
                            'Password',
                            'PeriodicInformEnable',
                            'PeriodicInformInterval',
                            'PeriodicInformTime',
                            'URL',
                            'UpgradesManaged',
                            'Username'])

    class Time(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.Time."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['CurrentLocalTime',
                            'DaylightSavingsEnd',
                            'DaylightSavingsStart',
                            'DaylightSavingsUsed',
                            'LocalTimeZone',
                            'LocalTimeZoneName',
                            'NTPServer1',
                            'NTPServer2',
                            'NTPServer3',
                            'NTPServer4',
                            'NTPServer5'])

    class UserInterface(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.UserInterface."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['AutoUpdateServer',
                            'BackgroundColor',
                            'ButtonColor',
                            'ButtonTextColor',
                            'ExampleLogin',
                            'ExamplePassword',
                            'ISPHelpDesk',
                            'ISPHelpPage',
                            'ISPHomePage',
                            'ISPLogo',
                            'ISPLogoSize',
                            'ISPMailServer',
                            'ISPName',
                            'ISPNewsServer',
                            'PasswordRequired',
                            'PasswordUserSelectable',
                            'TextColor',
                            'UpgradeAvailable',
                            'UserUpdateServer',
                            'WarrantyDate'])

    class WANDevice(core.Exporter):
      """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['WANConnectionNumberOfEntries'],
                    objects=['WANCommonInterfaceConfig',
                             'WANDSLConnectionManagement',
                             'WANDSLDiagnostics',
                             'WANDSLInterfaceConfig',
                             'WANEthernetInterfaceConfig'],
                    lists=['WANConnectionDevice'])

      class WANCommonInterfaceConfig(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['EnabledForInternet',
                              'Layer1DownstreamMaxBitRate',
                              'Layer1UpstreamMaxBitRate',
                              'MaximumActiveConnections',
                              'NumberOfActiveConnections',
                              'PhysicalLinkStatus',
                              'TotalBytesReceived',
                              'TotalBytesSent',
                              'TotalPacketsReceived',
                              'TotalPacketsSent',
                              'WANAccessProvider',
                              'WANAccessType'],
                      lists=['Connection'])

        class Connection(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig.Connection.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['ActiveConnectionDeviceContainer',
                                'ActiveConnectionServiceID'])

      class WANConnectionDevice(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['WANIPConnectionNumberOfEntries',
                              'WANPPPConnectionNumberOfEntries'],
                      objects=['WANATMF5LoopbackDiagnostics',
                               'WANDSLLinkConfig',
                               'WANEthernetLinkConfig',
                               'WANPOTSLinkConfig'],
                      lists=['WANIPConnection',
                             'WANPPPConnection'])

        class WANATMF5LoopbackDiagnostics(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AverageResponseTime',
                                'DiagnosticsState',
                                'FailureCount',
                                'MaximumResponseTime',
                                'MinimumResponseTime',
                                'NumberOfRepetitions',
                                'SuccessCount',
                                'Timeout'])

        class WANDSLLinkConfig(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AAL5CRCErrors',
                                'ATMAAL',
                                'ATMCRCErrors',
                                'ATMEncapsulation',
                                'ATMHECErrors',
                                'ATMMaximumBurstSize',
                                'ATMPeakCellRate',
                                'ATMQoS',
                                'ATMReceivedBlocks',
                                'ATMSustainableCellRate',
                                'ATMTransmittedBlocks',
                                'AutoConfig',
                                'DestinationAddress',
                                'Enable',
                                'FCSPreserved',
                                'LinkStatus',
                                'LinkType',
                                'ModulationType',
                                'VCSearchList'])

        class WANEthernetLinkConfig(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['EthernetLinkStatus'])

        class WANIPConnection(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AddressingType',
                                'AutoDisconnectTime',
                                'ConnectionStatus',
                                'ConnectionTrigger',
                                'ConnectionType',
                                'DNSEnabled',
                                'DNSOverrideAllowed',
                                'DNSServers',
                                'DefaultGateway',
                                'Enable',
                                'ExternalIPAddress',
                                'IdleDisconnectTime',
                                'LastConnectionError',
                                'MACAddress',
                                'MACAddressOverride',
                                'MaxMTUSize',
                                'NATEnabled',
                                'Name',
                                'PortMappingNumberOfEntries',
                                'PossibleConnectionTypes',
                                'RSIPAvailable',
                                'RouteProtocolRx',
                                'SubnetMask',
                                'Uptime',
                                'WarnDisconnectDelay'],
                        objects=['Stats'],
                        lists=['PortMapping'])

          class PortMapping(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ExternalPort',
                                  'InternalClient',
                                  'InternalPort',
                                  'PortMappingDescription',
                                  'PortMappingEnabled',
                                  'PortMappingLeaseDuration',
                                  'PortMappingProtocol',
                                  'RemoteHost'])

          class Stats(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['EthernetBytesReceived',
                                  'EthernetBytesSent',
                                  'EthernetPacketsReceived',
                                  'EthernetPacketsSent'])

        class WANPOTSLinkConfig(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPOTSLinkConfig."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['DataCompression',
                                'DataModulationSupported',
                                'DataProtocol',
                                'DelayBetweenRetries',
                                'Enable',
                                'Fclass',
                                'ISPInfo',
                                'ISPPhoneNumber',
                                'LinkStatus',
                                'LinkType',
                                'NumberOfRetries',
                                'PlusVTRCommandSupported'])

        class WANPPPConnection(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['AutoDisconnectTime',
                                'ConnectionStatus',
                                'ConnectionTrigger',
                                'ConnectionType',
                                'CurrentMRUSize',
                                'DNSEnabled',
                                'DNSOverrideAllowed',
                                'DNSServers',
                                'Enable',
                                'ExternalIPAddress',
                                'IdleDisconnectTime',
                                'LastConnectionError',
                                'MACAddress',
                                'MACAddressOverride',
                                'MaxMRUSize',
                                'NATEnabled',
                                'Name',
                                'PPPAuthenticationProtocol',
                                'PPPCompressionProtocol',
                                'PPPEncryptionProtocol',
                                'PPPLCPEcho',
                                'PPPLCPEchoRetry',
                                'PPPoEACName',
                                'PPPoEServiceName',
                                'Password',
                                'PortMappingNumberOfEntries',
                                'PossibleConnectionTypes',
                                'RSIPAvailable',
                                'RemoteIPAddress',
                                'RouteProtocolRx',
                                'TransportType',
                                'Uptime',
                                'Username',
                                'WarnDisconnectDelay'],
                        objects=['Stats'],
                        lists=['PortMapping'])

          class PortMapping(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ExternalPort',
                                  'InternalClient',
                                  'InternalPort',
                                  'PortMappingDescription',
                                  'PortMappingEnabled',
                                  'PortMappingLeaseDuration',
                                  'PortMappingProtocol',
                                  'RemoteHost'])

          class Stats(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['EthernetBytesReceived',
                                  'EthernetBytesSent',
                                  'EthernetPacketsReceived',
                                  'EthernetPacketsSent'])

      class WANDSLConnectionManagement(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLConnectionManagement."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['ConnectionServiceNumberOfEntries'],
                      lists=['ConnectionService'])

        class ConnectionService(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLConnectionManagement.ConnectionService.{i}."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['ConnectionType',
                                'DestinationAddress',
                                'LinkType',
                                'Name',
                                'WANConnectionDevice',
                                'WANConnectionService'])

      class WANDSLDiagnostics(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['ACTATPds',
                              'ACTATPus',
                              'ACTPSDds',
                              'ACTPSDus',
                              'BITSpsds',
                              'GAINSpsds',
                              'HLINSCds',
                              'HLINpsds',
                              'LoopDiagnosticsState',
                              'QLNpsds',
                              'SNRpsds'])

      class WANDSLInterfaceConfig(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['ATUCANSIRev',
                              'ATUCANSIStd',
                              'ATUCCountry',
                              'ATUCVendor',
                              'ATURANSIRev',
                              'ATURANSIStd',
                              'ATURCountry',
                              'ATURVendor',
                              'CurrentDayStart',
                              'DataPath',
                              'DownstreamAttenuation',
                              'DownstreamCurrRate',
                              'DownstreamMaxRate',
                              'DownstreamNoiseMargin',
                              'DownstreamPower',
                              'Enable',
                              'InterleaveDepth',
                              'LastShowtimeStart',
                              'LineEncoding',
                              'LineNumber',
                              'ModulationType',
                              'QuarterHourStart',
                              'ShowtimeStart',
                              'Status',
                              'TotalStart',
                              'UpstreamAttenuation',
                              'UpstreamCurrRate',
                              'UpstreamMaxRate',
                              'UpstreamNoiseMargin',
                              'UpstreamPower'],
                      objects=['Stats'])

        class Stats(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(objects=['CurrentDay',
                                 'LastShowtime',
                                 'QuarterHour',
                                 'Showtime',
                                 'Total'])

          class CurrentDay(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ATUCCRCErrors',
                                  'ATUCFECErrors',
                                  'ATUCHECErrors',
                                  'CRCErrors',
                                  'CellDelin',
                                  'ErroredSecs',
                                  'FECErrors',
                                  'HECErrors',
                                  'InitErrors',
                                  'InitTimeouts',
                                  'LinkRetrain',
                                  'LossOfFraming',
                                  'ReceiveBlocks',
                                  'SeverelyErroredSecs',
                                  'TransmitBlocks'])

          class LastShowtime(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.LastShowtime."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ATUCCRCErrors',
                                  'ATUCFECErrors',
                                  'ATUCHECErrors',
                                  'CRCErrors',
                                  'CellDelin',
                                  'ErroredSecs',
                                  'FECErrors',
                                  'HECErrors',
                                  'InitErrors',
                                  'InitTimeouts',
                                  'LinkRetrain',
                                  'LossOfFraming',
                                  'ReceiveBlocks',
                                  'SeverelyErroredSecs',
                                  'TransmitBlocks'])

          class QuarterHour(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ATUCCRCErrors',
                                  'ATUCFECErrors',
                                  'ATUCHECErrors',
                                  'CRCErrors',
                                  'CellDelin',
                                  'ErroredSecs',
                                  'FECErrors',
                                  'HECErrors',
                                  'InitErrors',
                                  'InitTimeouts',
                                  'LinkRetrain',
                                  'LossOfFraming',
                                  'ReceiveBlocks',
                                  'SeverelyErroredSecs',
                                  'TransmitBlocks'])

          class Showtime(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ATUCCRCErrors',
                                  'ATUCFECErrors',
                                  'ATUCHECErrors',
                                  'CRCErrors',
                                  'CellDelin',
                                  'ErroredSecs',
                                  'FECErrors',
                                  'HECErrors',
                                  'InitErrors',
                                  'InitTimeouts',
                                  'LinkRetrain',
                                  'LossOfFraming',
                                  'ReceiveBlocks',
                                  'SeverelyErroredSecs',
                                  'TransmitBlocks'])

          class Total(core.Exporter):
            """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total."""

            def __init__(self, **defaults):
              core.Exporter.__init__(self, defaults=defaults)
              self.Export(params=['ATUCCRCErrors',
                                  'ATUCFECErrors',
                                  'ATUCHECErrors',
                                  'CRCErrors',
                                  'CellDelin',
                                  'ErroredSecs',
                                  'FECErrors',
                                  'HECErrors',
                                  'InitErrors',
                                  'InitTimeouts',
                                  'LinkRetrain',
                                  'LossOfFraming',
                                  'ReceiveBlocks',
                                  'SeverelyErroredSecs',
                                  'TransmitBlocks'])

      class WANEthernetInterfaceConfig(core.Exporter):
        """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['DuplexMode',
                              'Enable',
                              'MACAddress',
                              'MaxBitRate',
                              'Status'],
                      objects=['Stats'])

        class Stats(core.Exporter):
          """Represents InternetGatewayDevice_v1_0.InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats."""

          def __init__(self, **defaults):
            core.Exporter.__init__(self, defaults=defaults)
            self.Export(params=['BytesReceived',
                                'BytesSent',
                                'PacketsReceived',
                                'PacketsSent'])



if __name__ == '__main__':
  print core.DumpSchema(InternetGatewayDevice_v1_0)
