#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:broadband-forum-org:tr-098-1-3."""

import core
from tr157_v1_3 import InternetGatewayDevice_v1_8


class InternetGatewayDevice_v1_9(InternetGatewayDevice_v1_8):
  """Represents InternetGatewayDevice_v1_9."""

  def __init__(self, **defaults):
    InternetGatewayDevice_v1_8.__init__(self, defaults=defaults)
    self.Export(objects=['DeviceInfo',
                         'DownloadAvailability',
                         'InternetGatewayDevice',
                         'ManagementServer',
                         'NSLookupDiagnostics',
                         'PeriodicStatistics',
                         'SoftwareModules',
                         'USBHosts'],
                lists=['SmartCardReader',
                       'User'])

  class DeviceInfo(InternetGatewayDevice_v1_8.DeviceInfo):
    """Represents InternetGatewayDevice_v1_9.DeviceInfo."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.DeviceInfo.__init__(self, defaults=defaults)
      self.Export(objects=['ProxierInfo',
                           'TemperatureStatus'],
                  lists=['Processor',
                         'SupportedDataModel',
                         'VendorLogFile'])

    class Processor(InternetGatewayDevice_v1_8.DeviceInfo.Processor):
      """Represents InternetGatewayDevice_v1_9.DeviceInfo.Processor.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.DeviceInfo.Processor.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

    class ProxierInfo(core.Exporter):
      """Represents InternetGatewayDevice_v1_9.DeviceInfo.ProxierInfo."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['ManufacturerOUI',
                            'ProductClass',
                            'ProxyProtocol',
                            'SerialNumber'])

    class SupportedDataModel(InternetGatewayDevice_v1_8.DeviceInfo.SupportedDataModel):
      """Represents InternetGatewayDevice_v1_9.DeviceInfo.SupportedDataModel.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.DeviceInfo.SupportedDataModel.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

    class TemperatureStatus(InternetGatewayDevice_v1_8.DeviceInfo.TemperatureStatus):
      """Represents InternetGatewayDevice_v1_9.DeviceInfo.TemperatureStatus."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.DeviceInfo.TemperatureStatus.__init__(self, defaults=defaults)
        self.Export(lists=['TemperatureSensor'])

      class TemperatureSensor(InternetGatewayDevice_v1_8.DeviceInfo.TemperatureStatus.TemperatureSensor):
        """Represents InternetGatewayDevice_v1_9.DeviceInfo.TemperatureStatus.TemperatureSensor.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.DeviceInfo.TemperatureStatus.TemperatureSensor.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class VendorLogFile(InternetGatewayDevice_v1_8.DeviceInfo.VendorLogFile):
      """Represents InternetGatewayDevice_v1_9.DeviceInfo.VendorLogFile.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.DeviceInfo.VendorLogFile.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

  class DownloadAvailability(InternetGatewayDevice_v1_8.DownloadAvailability):
    """Represents InternetGatewayDevice_v1_9.DownloadAvailability."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.DownloadAvailability.__init__(self, defaults=defaults)
      self.Export(objects=['Announcement'])

    class Announcement(InternetGatewayDevice_v1_8.DownloadAvailability.Announcement):
      """Represents InternetGatewayDevice_v1_9.DownloadAvailability.Announcement."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.DownloadAvailability.Announcement.__init__(self, defaults=defaults)
        self.Export(lists=['Group'])

      class Group(InternetGatewayDevice_v1_8.DownloadAvailability.Announcement.Group):
        """Represents InternetGatewayDevice_v1_9.DownloadAvailability.Announcement.Group.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.DownloadAvailability.Announcement.Group.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

  class InternetGatewayDevice(InternetGatewayDevice_v1_8.InternetGatewayDevice):
    """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.InternetGatewayDevice.__init__(self, defaults=defaults)
      self.Export(objects=['DeviceInfo',
                           'LANInterfaces',
                           'Layer2Bridging',
                           'Layer3Forwarding',
                           'ManagementServer',
                           'QueueManagement'],
                  lists=['LANDevice',
                         'WANDevice'])

    class DeviceInfo(InternetGatewayDevice_v1_8.InternetGatewayDevice.DeviceInfo):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.DeviceInfo."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.DeviceInfo.__init__(self, defaults=defaults)
        self.Export(params=['ManufacturerOUI',
                            'ProductClass',
                            'SerialNumber'],
                    lists=['VendorConfigFile'])

      class VendorConfigFile(InternetGatewayDevice_v1_8.InternetGatewayDevice.DeviceInfo.VendorConfigFile):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.DeviceInfo.VendorConfigFile.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class LANDevice(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.__init__(self, defaults=defaults)
        self.Export(params=['Alias'],
                    objects=['LANHostConfigManagement'],
                    lists=['LANEthernetInterfaceConfig',
                           'LANUSBInterfaceConfig',
                           'WLANConfiguration'])

      class LANEthernetInterfaceConfig(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANEthernetInterfaceConfig):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANEthernetInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class LANHostConfigManagement(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.__init__(self, defaults=defaults)
          self.Export(lists=['DHCPConditionalServingPool',
                             'DHCPOption',
                             'DHCPStaticAddress',
                             'IPInterface'])

        class DHCPConditionalServingPool(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool.__init__(self, defaults=defaults)
            self.Export(params=['Alias'],
                        lists=['DHCPOption',
                               'DHCPStaticAddress'])

          class DHCPOption(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool.DHCPOption):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool.DHCPOption.__init__(self, defaults=defaults)
              self.Export(params=['Alias'])

          class DHCPStaticAddress(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool.DHCPStaticAddress):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPStaticAddress.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPConditionalServingPool.DHCPStaticAddress.__init__(self, defaults=defaults)
              self.Export(params=['Alias'])

        class DHCPOption(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPOption):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPOption.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPOption.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class DHCPStaticAddress(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPStaticAddress):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.DHCPStaticAddress.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class IPInterface(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.IPInterface):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANHostConfigManagement.IPInterface.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

      class LANUSBInterfaceConfig(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANUSBInterfaceConfig):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.LANUSBInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class WLANConfiguration(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.__init__(self, defaults=defaults)
          self.Export(params=['Alias'],
                      objects=['WPS'],
                      lists=['APWMMParameter',
                             'PreSharedKey',
                             'STAWMMParameter',
                             'WEPKey'])

        class APWMMParameter(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.APWMMParameter):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.APWMMParameter.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.APWMMParameter.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class PreSharedKey(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.PreSharedKey):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.PreSharedKey.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class STAWMMParameter(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.STAWMMParameter):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.STAWMMParameter.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.STAWMMParameter.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class WEPKey(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WEPKey):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WEPKey.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class WPS(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WPS):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WPS.__init__(self, defaults=defaults)
            self.Export(lists=['Registrar'])

          class Registrar(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WPS.Registrar):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS.Registrar.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.LANDevice.WLANConfiguration.WPS.Registrar.__init__(self, defaults=defaults)
              self.Export(params=['Alias'])

    class LANInterfaces(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANInterfaces."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.__init__(self, defaults=defaults)
        self.Export(lists=['LANEthernetInterfaceConfig',
                           'LANUSBInterfaceConfig',
                           'WLANConfiguration'])

      class LANEthernetInterfaceConfig(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.LANEthernetInterfaceConfig):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANInterfaces.LANEthernetInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.LANEthernetInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class LANUSBInterfaceConfig(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.LANUSBInterfaceConfig):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANInterfaces.LANUSBInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.LANUSBInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class WLANConfiguration(InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.WLANConfiguration):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.LANInterfaces.WLANConfiguration.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class Layer2Bridging(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.__init__(self, defaults=defaults)
        self.Export(lists=['AvailableInterface',
                           'Bridge',
                           'Filter',
                           'Marking'])

      class AvailableInterface(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.AvailableInterface):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.AvailableInterface.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Bridge(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.Bridge.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge.__init__(self, defaults=defaults)
          self.Export(params=['Alias'],
                      lists=['Port',
                             'VLAN'])

        class Port(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge.Port):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.Bridge.{i}.Port.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge.Port.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

        class VLAN(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge.VLAN):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.Bridge.{i}.VLAN.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Bridge.VLAN.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

      class Filter(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Filter):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.Filter.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Filter.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Marking(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Marking):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer2Bridging.Marking.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer2Bridging.Marking.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class Layer3Forwarding(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer3Forwarding):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer3Forwarding."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer3Forwarding.__init__(self, defaults=defaults)
        self.Export(lists=['Forwarding'])

      class Forwarding(InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer3Forwarding.Forwarding):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.Layer3Forwarding.Forwarding.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class ManagementServer(InternetGatewayDevice_v1_8.InternetGatewayDevice.ManagementServer):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.ManagementServer."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.ManagementServer.__init__(self, defaults=defaults)
        self.Export(params=['AliasBasedAddressing',
                            'AutoCreateInstances',
                            'CWMPRetryIntervalMultiplier',
                            'CWMPRetryMinimumWaitInterval',
                            'InstanceMode'])

    class QueueManagement(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.__init__(self, defaults=defaults)
        self.Export(lists=['App',
                           'Classification',
                           'Flow',
                           'Policer',
                           'Queue',
                           'QueueStats'])

      class App(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.App):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.App.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.App.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Classification(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Classification):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.Classification.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Classification.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Flow(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Flow):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.Flow.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Flow.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Policer(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Policer):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.Policer.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Policer.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class Queue(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Queue):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.Queue.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.Queue.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

      class QueueStats(InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.QueueStats):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.QueueManagement.QueueStats.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.QueueManagement.QueueStats.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

    class WANDevice(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice):
      """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.__init__(self, defaults=defaults)
        self.Export(params=['Alias'],
                    objects=['WANCommonInterfaceConfig'],
                    lists=['WANConnectionDevice'])

      class WANCommonInterfaceConfig(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(lists=['Connection'])

        class Connection(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig.Connection):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig.Connection.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig.Connection.__init__(self, defaults=defaults)
            self.Export(params=['Alias'])

      class WANConnectionDevice(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice):
        """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.__init__(self, defaults=defaults)
          self.Export(params=['Alias'],
                      lists=['WANIPConnection',
                             'WANPPPConnection'])

        class WANIPConnection(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.__init__(self, defaults=defaults)
            self.Export(params=['Alias'],
                        objects=['DHCPClient'],
                        lists=['PortMapping'])

          class DHCPClient(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.DHCPClient."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient.__init__(self, defaults=defaults)
              self.Export(lists=['ReqDHCPOption',
                                 'SentDHCPOption'])

            class ReqDHCPOption(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient.ReqDHCPOption):
              """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.DHCPClient.ReqDHCPOption.{i}."""

              def __init__(self, **defaults):
                InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient.ReqDHCPOption.__init__(self, defaults=defaults)
                self.Export(params=['Alias'])

            class SentDHCPOption(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient.SentDHCPOption):
              """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.DHCPClient.SentDHCPOption.{i}."""

              def __init__(self, **defaults):
                InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.DHCPClient.SentDHCPOption.__init__(self, defaults=defaults)
                self.Export(params=['Alias'])

          class PortMapping(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.PortMapping):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.PortMapping.__init__(self, defaults=defaults)
              self.Export(params=['Alias'])

        class WANPPPConnection(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection):
          """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.__init__(self, defaults=defaults)
            self.Export(params=['Alias'],
                        lists=['PortMapping'])

          class PortMapping(InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.PortMapping):
            """Represents InternetGatewayDevice_v1_9.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_8.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.PortMapping.__init__(self, defaults=defaults)
              self.Export(params=['Alias'])

  class ManagementServer(InternetGatewayDevice_v1_8.ManagementServer):
    """Represents InternetGatewayDevice_v1_9.ManagementServer."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.ManagementServer.__init__(self, defaults=defaults)
      self.Export(params=['EmbeddedDeviceNumberOfEntries',
                          'VirtualDeviceNumberOfEntries'],
                  lists=['EmbeddedDevice',
                         'VirtualDevice'])

    class EmbeddedDevice(core.Exporter):
      """Represents InternetGatewayDevice_v1_9.ManagementServer.EmbeddedDevice.{i}."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['CommandProcessed',
                            'CommandProcessingErrMsg',
                            'ControllerID',
                            'Host',
                            'LastSyncTime',
                            'ProxiedDeviceID',
                            'ProxyProtocol',
                            'Reference',
                            'SupportedDataModel'])

    class VirtualDevice(core.Exporter):
      """Represents InternetGatewayDevice_v1_9.ManagementServer.VirtualDevice.{i}."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['Host',
                            'ManufacturerOUI',
                            'ProductClass',
                            'ProxyProtocol',
                            'SerialNumber'])

  class NSLookupDiagnostics(InternetGatewayDevice_v1_8.NSLookupDiagnostics):
    """Represents InternetGatewayDevice_v1_9.NSLookupDiagnostics."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.NSLookupDiagnostics.__init__(self, defaults=defaults)
      self.Export(params=['DiagnosticsState'])

  class PeriodicStatistics(InternetGatewayDevice_v1_8.PeriodicStatistics):
    """Represents InternetGatewayDevice_v1_9.PeriodicStatistics."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.PeriodicStatistics.__init__(self, defaults=defaults)
      self.Export(lists=['SampleSet'])

    class SampleSet(InternetGatewayDevice_v1_8.PeriodicStatistics.SampleSet):
      """Represents InternetGatewayDevice_v1_9.PeriodicStatistics.SampleSet.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.PeriodicStatistics.SampleSet.__init__(self, defaults=defaults)
        self.Export(params=['Alias'],
                    lists=['Parameter'])

      class Parameter(InternetGatewayDevice_v1_8.PeriodicStatistics.SampleSet.Parameter):
        """Represents InternetGatewayDevice_v1_9.PeriodicStatistics.SampleSet.{i}.Parameter.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_8.PeriodicStatistics.SampleSet.Parameter.__init__(self, defaults=defaults)
          self.Export(params=['Alias'])

  class SmartCardReader(InternetGatewayDevice_v1_8.SmartCardReader):
    """Represents InternetGatewayDevice_v1_9.SmartCardReader.{i}."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.SmartCardReader.__init__(self, defaults=defaults)
      self.Export(params=['Alias'])

  class SoftwareModules(InternetGatewayDevice_v1_8.SoftwareModules):
    """Represents InternetGatewayDevice_v1_9.SoftwareModules."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.SoftwareModules.__init__(self, defaults=defaults)
      self.Export(lists=['DeploymentUnit',
                         'ExecEnv',
                         'ExecutionUnit'])

    class DeploymentUnit(InternetGatewayDevice_v1_8.SoftwareModules.DeploymentUnit):
      """Represents InternetGatewayDevice_v1_9.SoftwareModules.DeploymentUnit.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.SoftwareModules.DeploymentUnit.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

    class ExecEnv(InternetGatewayDevice_v1_8.SoftwareModules.ExecEnv):
      """Represents InternetGatewayDevice_v1_9.SoftwareModules.ExecEnv.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.SoftwareModules.ExecEnv.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

    class ExecutionUnit(InternetGatewayDevice_v1_8.SoftwareModules.ExecutionUnit):
      """Represents InternetGatewayDevice_v1_9.SoftwareModules.ExecutionUnit.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.SoftwareModules.ExecutionUnit.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

  class USBHosts(InternetGatewayDevice_v1_8.USBHosts):
    """Represents InternetGatewayDevice_v1_9.USBHosts."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.USBHosts.__init__(self, defaults=defaults)
      self.Export(lists=['Host'])

    class Host(InternetGatewayDevice_v1_8.USBHosts.Host):
      """Represents InternetGatewayDevice_v1_9.USBHosts.Host.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_8.USBHosts.Host.__init__(self, defaults=defaults)
        self.Export(params=['Alias'])

  class User(InternetGatewayDevice_v1_8.User):
    """Represents InternetGatewayDevice_v1_9.User.{i}."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_8.User.__init__(self, defaults=defaults)
      self.Export(params=['Alias'])


if __name__ == '__main__':
  print core.DumpSchema(InternetGatewayDevice_v1_9)
