#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:broadband-forum-org:tr-098-1-1."""

import core
from tr098_v1_0 import InternetGatewayDevice_v1_1


class InternetGatewayDevice_v1_2(InternetGatewayDevice_v1_1):
  """Represents InternetGatewayDevice_v1_2."""

  def __init__(self, **defaults):
    InternetGatewayDevice_v1_1.__init__(self, defaults=defaults)
    self.Export(objects=['InternetGatewayDevice'])

  class InternetGatewayDevice(InternetGatewayDevice_v1_1.InternetGatewayDevice):
    """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice."""

    def __init__(self, **defaults):
      InternetGatewayDevice_v1_1.InternetGatewayDevice.__init__(self, defaults=defaults)
      self.Export(objects=['DeviceConfig',
                           'DeviceInfo',
                           'IPPingDiagnostics',
                           'LANConfigSecurity',
                           'Layer2Bridging',
                           'Layer3Forwarding',
                           'ManagementServer',
                           'QueueManagement',
                           'Time',
                           'UserInterface'],
                  lists=['LANDevice',
                         'WANDevice'])

    class DeviceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceConfig):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.DeviceConfig."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceConfig.__init__(self, defaults=defaults)
        self.Export(params=['ConfigFile',
                            'PersistentData'])

    class DeviceInfo(InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceInfo):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.DeviceInfo."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceInfo.__init__(self, defaults=defaults)
        self.Export(params=['AdditionalHardwareVersion',
                            'AdditionalSoftwareVersion',
                            'EnabledOptions',
                            'FirstUseDate',
                            'ProvisioningCode',
                            'SpecVersion'],
                    lists=['VendorConfigFile'])

      class VendorConfigFile(InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceInfo.VendorConfigFile):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.DeviceInfo.VendorConfigFile.__init__(self, defaults=defaults)
          self.Export(params=['Name',
                              'Version'])

    class IPPingDiagnostics(InternetGatewayDevice_v1_1.InternetGatewayDevice.IPPingDiagnostics):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.IPPingDiagnostics."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.IPPingDiagnostics.__init__(self, defaults=defaults)
        self.Export(params=['DSCP',
                            'DiagnosticsState',
                            'Interface'])

    class LANConfigSecurity(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANConfigSecurity):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANConfigSecurity."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.LANConfigSecurity.__init__(self, defaults=defaults)
        self.Export(params=['ConfigPassword'])

    class LANDevice(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.__init__(self, defaults=defaults)
        self.Export(objects=['Hosts',
                             'LANHostConfigManagement'],
                    lists=['LANEthernetInterfaceConfig',
                           'LANUSBInterfaceConfig',
                           'WLANConfiguration'])

      class Hosts(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.Hosts):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.Hosts."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.Hosts.__init__(self, defaults=defaults)
          self.Export(lists=['Host'])

        class Host(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.Hosts.Host):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.Hosts.Host.__init__(self, defaults=defaults)
            self.Export(params=['Active',
                                'LeaseTimeRemaining'])

      class LANEthernetInterfaceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANEthernetInterfaceConfig):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANEthernetInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Status'])

      class LANHostConfigManagement(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANHostConfigManagement):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANHostConfigManagement.__init__(self, defaults=defaults)
          self.Export(params=['AllowedMACAddresses',
                              'DHCPRelay',
                              'DHCPServerConfigurable',
                              'DNSServers',
                              'IPInterfaceNumberOfEntries',
                              'IPRouters',
                              'PassthroughLease',
                              'ReservedAddresses'],
                      lists=['IPInterface'])

        class IPInterface(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANHostConfigManagement.IPInterface):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANHostConfigManagement.IPInterface.__init__(self, defaults=defaults)
            self.Export(params=['IPInterfaceAddressingType',
                                'IPInterfaceIPAddress',
                                'IPInterfaceSubnetMask'])

      class LANUSBInterfaceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANUSBInterfaceConfig):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.LANUSBInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Status'])

      class WLANConfiguration(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.__init__(self, defaults=defaults)
          self.Export(params=['BasicAuthenticationMode',
                              'BasicEncryptionModes',
                              'BeaconType',
                              'Enable',
                              'IEEE11iAuthenticationMode',
                              'IEEE11iEncryptionModes',
                              'KeyPassphrase',
                              'SSID',
                              'Standard',
                              'Status',
                              'WEPEncryptionLevel',
                              'WPAAuthenticationMode',
                              'WPAEncryptionModes'],
                      lists=['AssociatedDevice',
                             'PreSharedKey',
                             'WEPKey'])

        class AssociatedDevice(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.AssociatedDevice):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}."""
          pass

        class PreSharedKey(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.PreSharedKey):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.PreSharedKey.__init__(self, defaults=defaults)
            self.Export(params=['KeyPassphrase',
                                'PreSharedKey'])

        class WEPKey(InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.WEPKey):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.LANDevice.WLANConfiguration.WEPKey.__init__(self, defaults=defaults)
            self.Export(params=['WEPKey'])

    class Layer2Bridging(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer2Bridging."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.__init__(self, defaults=defaults)
        self.Export(params=['AvailableInterfaceNumberOfEntries'],
                    lists=['AvailableInterface',
                           'Bridge',
                           'Filter',
                           'Marking'])

      class AvailableInterface(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.AvailableInterface):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.AvailableInterface.__init__(self, defaults=defaults)
          self.Export(params=['InterfaceReference'])

      class Bridge(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Bridge):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer2Bridging.Bridge.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Bridge.__init__(self, defaults=defaults)
          self.Export(params=['BridgeStatus'])

      class Filter(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Filter):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer2Bridging.Filter.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Filter.__init__(self, defaults=defaults)
          self.Export(params=['DestMACAddressFilterList',
                              'FilterStatus',
                              'SourceMACAddressFilterList',
                              'VLANIDFilter'])

      class Marking(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Marking):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer2Bridging.Marking.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer2Bridging.Marking.__init__(self, defaults=defaults)
          self.Export(params=['MarkingStatus',
                              'VLANIDMark'])

    class Layer3Forwarding(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer3Forwarding):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer3Forwarding."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer3Forwarding.__init__(self, defaults=defaults)
        self.Export(lists=['Forwarding'])

      class Forwarding(InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer3Forwarding.Forwarding):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.Layer3Forwarding.Forwarding.__init__(self, defaults=defaults)
          self.Export(params=['DestIPAddress',
                              'DestSubnetMask',
                              'ForwardingMetric',
                              'GatewayIPAddress',
                              'Interface',
                              'SourceIPAddress',
                              'SourceSubnetMask',
                              'Status',
                              'Type'])

    class ManagementServer(InternetGatewayDevice_v1_1.InternetGatewayDevice.ManagementServer):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.ManagementServer."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.ManagementServer.__init__(self, defaults=defaults)
        self.Export(params=['ConnectionRequestURL',
                            'DownloadProgressURL',
                            'KickURL',
                            'ManageableDeviceNotificationLimit',
                            'ManageableDeviceNumberOfEntries',
                            'NATDetected',
                            'Password',
                            'PeriodicInformEnable',
                            'PeriodicInformTime',
                            'STUNEnable',
                            'STUNMaximumKeepAlivePeriod',
                            'STUNMinimumKeepAlivePeriod',
                            'STUNPassword',
                            'STUNServerAddress',
                            'STUNServerPort',
                            'STUNUsername',
                            'UDPConnectionRequestAddress',
                            'UDPConnectionRequestAddressNotificationLimit',
                            'URL',
                            'UpgradesManaged',
                            'Username'],
                    lists=['ManageableDevice'])

      class ManageableDevice(core.Exporter):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.ManagementServer.ManageableDevice.{i}."""

        def __init__(self, **defaults):
          core.Exporter.__init__(self, defaults=defaults)
          self.Export(params=['ManufacturerOUI',
                              'ProductClass',
                              'SerialNumber'])

    class QueueManagement(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.__init__(self, defaults=defaults)
        self.Export(params=['AvailableAppList',
                            'DefaultDSCPMark',
                            'DefaultEthernetPriorityMark'],
                    lists=['App',
                           'Classification',
                           'Flow',
                           'Policer',
                           'Queue'])

      class App(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.App):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement.App.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.App.__init__(self, defaults=defaults)
          self.Export(params=['AppDefaultDSCPMark',
                              'AppDefaultEthernetPriorityMark',
                              'AppKey',
                              'AppStatus',
                              'ProtocolIdentifier'])

      class Classification(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Classification):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement.Classification.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Classification.__init__(self, defaults=defaults)
          self.Export(params=['ClassApp',
                              'ClassInterface',
                              'ClassQueue',
                              'ClassificationKey',
                              'ClassificationOrder',
                              'ClassificationStatus',
                              'DSCPMark',
                              'EthernetPriorityMark'])

      class Flow(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Flow):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement.Flow.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Flow.__init__(self, defaults=defaults)
          self.Export(params=['FlowDSCPMark',
                              'FlowEthernetPriorityMark',
                              'FlowKey',
                              'FlowStatus',
                              'FlowType'])

      class Policer(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Policer):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement.Policer.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Policer.__init__(self, defaults=defaults)
          self.Export(params=['PolicerKey',
                              'PolicerStatus'])

      class Queue(InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Queue):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.QueueManagement.Queue.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.QueueManagement.Queue.__init__(self, defaults=defaults)
          self.Export(params=['DropAlgorithm',
                              'QueueBufferLength',
                              'QueueInterface',
                              'QueueKey',
                              'QueueStatus',
                              'REDPercentage',
                              'REDThreshold',
                              'SchedulerAlgorithm',
                              'ShapingBurstSize',
                              'ShapingRate'])

    class Time(InternetGatewayDevice_v1_1.InternetGatewayDevice.Time):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.Time."""
      pass

    class UserInterface(InternetGatewayDevice_v1_1.InternetGatewayDevice.UserInterface):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.UserInterface."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.UserInterface.__init__(self, defaults=defaults)
        self.Export(params=['PasswordRequired',
                            'PasswordUserSelectable'])

    class WANDevice(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice):
      """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}."""

      def __init__(self, **defaults):
        InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.__init__(self, defaults=defaults)
        self.Export(objects=['WANCommonInterfaceConfig',
                             'WANDSLConnectionManagement',
                             'WANDSLDiagnostics',
                             'WANDSLInterfaceConfig',
                             'WANEthernetInterfaceConfig'],
                    lists=['WANConnectionDevice'])

      class WANCommonInterfaceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANCommonInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Layer1DownstreamMaxBitRate',
                              'Layer1UpstreamMaxBitRate'])

      class WANConnectionDevice(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.__init__(self, defaults=defaults)
          self.Export(objects=['WANATMF5LoopbackDiagnostics',
                               'WANDSLLinkConfig',
                               'WANPOTSLinkConfig'],
                      lists=['WANIPConnection',
                             'WANPPPConnection'])

        class WANATMF5LoopbackDiagnostics(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANATMF5LoopbackDiagnostics):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANATMF5LoopbackDiagnostics.__init__(self, defaults=defaults)
            self.Export(params=['AverageResponseTime',
                                'DiagnosticsState',
                                'FailureCount',
                                'MaximumResponseTime',
                                'MinimumResponseTime',
                                'NumberOfRepetitions',
                                'SuccessCount'])

        class WANDSLLinkConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANDSLLinkConfig):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANDSLLinkConfig.__init__(self, defaults=defaults)
            self.Export(params=['AAL5CRCErrors',
                                'ATMCRCErrors',
                                'ATMReceivedBlocks',
                                'ATMTransmittedBlocks',
                                'AutoConfig',
                                'DestinationAddress',
                                'FCSPreserved',
                                'LinkType'])

        class WANIPConnection(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.__init__(self, defaults=defaults)
            self.Export(params=['ConnectionTrigger',
                                'DNSEnabled',
                                'DNSOverrideAllowed',
                                'DNSServers',
                                'LastConnectionError',
                                'RouteProtocolRx',
                                'ShapingBurstSize',
                                'ShapingRate'],
                        objects=['Stats'],
                        lists=['PortMapping'])

          class PortMapping(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.PortMapping):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.PortMapping.__init__(self, defaults=defaults)
              self.Export(params=['ExternalPort',
                                  'InternalClient',
                                  'InternalPort',
                                  'PortMappingDescription',
                                  'PortMappingLeaseDuration',
                                  'PortMappingProtocol',
                                  'RemoteHost'])

          class Stats(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANIPConnection.Stats):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats."""
            pass

        class WANPOTSLinkConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPOTSLinkConfig):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPOTSLinkConfig."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPOTSLinkConfig.__init__(self, defaults=defaults)
            self.Export(params=['DelayBetweenRetries',
                                'ISPInfo',
                                'ISPPhoneNumber',
                                'LinkType',
                                'NumberOfRetries'])

        class WANPPPConnection(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.__init__(self, defaults=defaults)
            self.Export(params=['ConnectionTrigger',
                                'DNSEnabled',
                                'DNSOverrideAllowed',
                                'DNSServers',
                                'LastConnectionError',
                                'MACAddress',
                                'MACAddressOverride',
                                'PPPoEACName',
                                'PPPoEServiceName',
                                'Password',
                                'RouteProtocolRx',
                                'ShapingBurstSize',
                                'ShapingRate',
                                'Username'],
                        objects=['Stats'],
                        lists=['PortMapping'])

          class PortMapping(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.PortMapping):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.PortMapping.__init__(self, defaults=defaults)
              self.Export(params=['ExternalPort',
                                  'InternalClient',
                                  'InternalPort',
                                  'PortMappingDescription',
                                  'PortMappingLeaseDuration',
                                  'PortMappingProtocol',
                                  'RemoteHost'])

          class Stats(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANConnectionDevice.WANPPPConnection.Stats):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats."""
            pass

      class WANDSLConnectionManagement(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLConnectionManagement):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLConnectionManagement."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLConnectionManagement.__init__(self, defaults=defaults)
          self.Export(params=['ConnectionServiceNumberOfEntries'],
                      lists=['ConnectionService'])

        class ConnectionService(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLConnectionManagement.ConnectionService):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLConnectionManagement.ConnectionService.{i}."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLConnectionManagement.ConnectionService.__init__(self, defaults=defaults)
            self.Export(params=['ConnectionType',
                                'DestinationAddress',
                                'LinkType',
                                'Name',
                                'WANConnectionDevice',
                                'WANConnectionService'])

      class WANDSLDiagnostics(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLDiagnostics):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLDiagnostics.__init__(self, defaults=defaults)
          self.Export(params=['LoopDiagnosticsState'])

      class WANDSLInterfaceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['ATUCCountry',
                              'ATUCVendor',
                              'ATURCountry',
                              'ATURVendor',
                              'CurrentDayStart',
                              'DownstreamCurrRate',
                              'InterleaveDepth',
                              'QuarterHourStart',
                              'ShowtimeStart',
                              'Status',
                              'TotalStart',
                              'UpstreamCurrRate'],
                      objects=['Stats'])

        class Stats(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats):
          """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats."""

          def __init__(self, **defaults):
            InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.__init__(self, defaults=defaults)
            self.Export(objects=['CurrentDay',
                                 'LastShowtime',
                                 'QuarterHour',
                                 'Showtime',
                                 'Total'])

          class CurrentDay(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.CurrentDay):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.CurrentDay.__init__(self, defaults=defaults)
              self.Export(params=['ReceiveBlocks',
                                  'TransmitBlocks'])

          class LastShowtime(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.LastShowtime):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.LastShowtime."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.LastShowtime.__init__(self, defaults=defaults)
              self.Export(params=['ReceiveBlocks',
                                  'TransmitBlocks'])

          class QuarterHour(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.QuarterHour):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.QuarterHour.__init__(self, defaults=defaults)
              self.Export(params=['ReceiveBlocks',
                                  'TransmitBlocks'])

          class Showtime(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.Showtime):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.Showtime.__init__(self, defaults=defaults)
              self.Export(params=['ReceiveBlocks',
                                  'TransmitBlocks'])

          class Total(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.Total):
            """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total."""

            def __init__(self, **defaults):
              InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANDSLInterfaceConfig.Stats.Total.__init__(self, defaults=defaults)
              self.Export(params=['ReceiveBlocks',
                                  'TransmitBlocks'])

      class WANEthernetInterfaceConfig(InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANEthernetInterfaceConfig):
        """Represents InternetGatewayDevice_v1_2.InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig."""

        def __init__(self, **defaults):
          InternetGatewayDevice_v1_1.InternetGatewayDevice.WANDevice.WANEthernetInterfaceConfig.__init__(self, defaults=defaults)
          self.Export(params=['Status'])


if __name__ == '__main__':
  print core.DumpSchema(InternetGatewayDevice_v1_2)
