#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:broadband-forum-org:tr-140-1-1."""

import core
from tr140_v1_0 import StorageService_v1_0


class StorageService_v1_1(StorageService_v1_0):
  """Represents StorageService_v1_1."""

  def __init__(self, **defaults):
    StorageService_v1_0.__init__(self, defaults=defaults)
    self.Export(params=['StorageServiceNumberOfEntries'],
                lists=['StorageService'])

  class StorageService(StorageService_v1_0.StorageService):
    """Represents StorageService_v1_1.StorageService.{i}."""

    def __init__(self, **defaults):
      StorageService_v1_0.StorageService.__init__(self, defaults=defaults)
      self.Export(lists=['LogicalVolume'])

    class LogicalVolume(StorageService_v1_0.StorageService.LogicalVolume):
      """Represents StorageService_v1_1.StorageService.{i}.LogicalVolume.{i}."""

      def __init__(self, **defaults):
        StorageService_v1_0.StorageService.LogicalVolume.__init__(self, defaults=defaults)
        self.Export(lists=['Folder'])

      class Folder(StorageService_v1_0.StorageService.LogicalVolume.Folder):
        """Represents StorageService_v1_1.StorageService.{i}.LogicalVolume.{i}.Folder.{i}."""

        def __init__(self, **defaults):
          StorageService_v1_0.StorageService.LogicalVolume.Folder.__init__(self, defaults=defaults)
          self.Export(lists=['GroupAccess',
                             'UserAccess'])

        class GroupAccess(StorageService_v1_0.StorageService.LogicalVolume.Folder.GroupAccess):
          """Represents StorageService_v1_1.StorageService.{i}.LogicalVolume.{i}.Folder.{i}.GroupAccess.{i}."""

          def __init__(self, **defaults):
            StorageService_v1_0.StorageService.LogicalVolume.Folder.GroupAccess.__init__(self, defaults=defaults)
            self.Export(params=['Enable'])

        class UserAccess(StorageService_v1_0.StorageService.LogicalVolume.Folder.UserAccess):
          """Represents StorageService_v1_1.StorageService.{i}.LogicalVolume.{i}.Folder.{i}.UserAccess.{i}."""

          def __init__(self, **defaults):
            StorageService_v1_0.StorageService.LogicalVolume.Folder.UserAccess.__init__(self, defaults=defaults)
            self.Export(params=['Enable'])


if __name__ == '__main__':
  print core.DumpSchema(StorageService_v1_1)
