#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:catawampus-org:x-catawampus-1-0."""

import core


class X_CATAWAMPUS_ORG_CATAWAMPUS_v1_0(core.Exporter):
  """Represents X_CATAWAMPUS_ORG_CATAWAMPUS_v1_0."""

  def __init__(self, **defaults):
    core.Exporter.__init__(self, defaults=defaults)
    self.Export(params=['RuntimeEnvInfo'])


if __name__ == '__main__':
  print core.DumpSchema(X_CATAWAMPUS_ORG_CATAWAMPUS_v1_0)
