#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
# AUTO-GENERATED BY parse-schema.py
#
# DO NOT EDIT!!
#
#pylint: disable-msg=C6202
#pylint: disable-msg=C6409
#pylint: disable-msg=C6310
# These should not actually be necessary (bugs in gpylint?):
#pylint: disable-msg=E1101
#pylint: disable-msg=W0231
#
"""Auto-generated from spec: urn:google-com:x-gfibertv-1-0."""

import core


class X_GOOGLE_COM_GFIBERTV_v1_0(core.Exporter):
  """Represents X_GOOGLE_COM_GFIBERTV_v1_0."""

  def __init__(self, **defaults):
    core.Exporter.__init__(self, defaults=defaults)
    self.Export(objects=['X_GOOGLE_COM_GFIBERTV'])

  class X_GOOGLE_COM_GFIBERTV(core.Exporter):
    """Represents X_GOOGLE_COM_GFIBERTV_v1_0.X_GOOGLE_COM_GFIBERTV."""

    def __init__(self, **defaults):
      core.Exporter.__init__(self, defaults=defaults)
      self.Export(params=['BtConfig',
                          'BtDevices',
                          'BtHHDevices',
                          'BtNoPairing',
                          'DevicePropertiesNumberOfEntries'],
                  objects=['Mailbox'],
                  lists=['DeviceProperties'])

    class DeviceProperties(core.Exporter):
      """Represents X_GOOGLE_COM_GFIBERTV_v1_0.X_GOOGLE_COM_GFIBERTV.DeviceProperties.{i}."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['NickName',
                            'SerialNumber'])

    class Mailbox(core.Exporter):
      """Represents X_GOOGLE_COM_GFIBERTV_v1_0.X_GOOGLE_COM_GFIBERTV.Mailbox."""

      def __init__(self, **defaults):
        core.Exporter.__init__(self, defaults=defaults)
        self.Export(params=['Name',
                            'Node',
                            'NodeList',
                            'Value'])


if __name__ == '__main__':
  print core.DumpSchema(X_GOOGLE_COM_GFIBERTV_v1_0)
