#!/bin/sh

if [ -n $TESTOUTPUT ]; then
  echo $* >$TESTOUTPUT
fi

if [ $1 == 'cwmp' ] && [ $2 == 'foo' ]; then
  exit 0
fi

if [ $1 == 'cwmp' ] && [ $2 == 'clear' ]; then
  exit 0
fi

if [ $1 == 'print' ]; then
  echo -n 'bar'
  exit 0
fi

exit 1
